from enum import Enum

class EGenre(Enum):
    ALL=""
    Action="Action"
    ActionAdventure="Action-Adventure"
    Adventure="Adventure"
    BoardGame="Board Game"
    Education="Education"
    Fighting="Fighting"
    Misc="Misc"
    MMO="MMO"
    Music="Music"
    Party="Party"
    Platform="Platform"
    Puzzle="Puzzle"
    Racing="Racing"
    RolePlaying="Role-Playing"
    Sandbox="Sandbox"
    Shooter="Shooter"
    Simulation="Simulation"
    Sports="Sports"
    Strategy="Strategy"
    VisualNovel="Visual Novel"